### ISSUE TITLE
IIFE OPTIONAL:

### ISSUE THREAD

**Issue by elizawmeeks** [nss-day-cohort-19/d19-group-chatty-take2-ecm#11]
Chatty.navClear
Chatty.enterKeyPress
Chatty.selectTheme
Chatty.deleteButton

**Comment by augsismyburger** [comment]
Nav clear can be tested when enterKeyPress function is finished.
Currently working on enterKeyPress function.

**Comment by chazhenricks** [comment]
delete keys work
